export const mockAppointments = [
  {
    id: '1',
    patientId: '1',
    dermatologistId: '1',
    dermatologistName: 'Dr. Sarah Johnson',
    date: '2024-12-20',
    time: '10:00',
    status: 'confirmed',
    type: 'consultation',
    caseId: 'case-1',
    notes: 'Follow-up for alopecia treatment',
  },
  {
    id: '2',
    patientId: '1',
    dermatologistId: '2',
    dermatologistName: 'Dr. Michael Chen',
    date: '2024-12-22',
    time: '14:00',
    status: 'pending',
    type: 'consultation',
    caseId: null,
    notes: '',
  },
  {
    id: '3',
    patientId: '2',
    dermatologistId: '1',
    dermatologistName: 'Dr. Sarah Johnson',
    date: '2024-12-18',
    time: '11:00',
    status: 'completed',
    type: 'follow-up',
    caseId: 'case-2',
    notes: 'Progress check on treatment plan',
  },
]
