export const mockDermatologists = [
  {
    id: '1',
    name: 'Dr. Sarah Johnson',
    email: 'sarah.johnson@dermmate.com',
    phone: '+1234567800',
    specialization: 'Hair Disorders, Alopecia',
    experience: 12,
    rating: 4.8,
    totalReviews: 234,
    location: {
      city: 'New York',
      state: 'NY',
      address: '123 Medical Plaza, Suite 200',
      coordinates: { lat: 40.7128, lng: -74.0060 },
    },
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    certificationStatus: 'approved',
    availableSlots: ['09:00', '10:00', '11:00', '14:00', '15:00'],
    bio: 'Board-certified dermatologist with expertise in hair loss and scalp disorders.',
    education: ['MD, Harvard Medical School', 'Residency: Johns Hopkins'],
    languages: ['English', 'Spanish'],
  },
  {
    id: '2',
    name: 'Dr. Michael Chen',
    email: 'michael.chen@dermmate.com',
    phone: '+1234567801',
    specialization: 'Skin Conditions, Acne',
    experience: 8,
    rating: 4.9,
    totalReviews: 189,
    location: {
      city: 'Los Angeles',
      state: 'CA',
      address: '456 Health Center, Floor 3',
      coordinates: { lat: 34.0522, lng: -118.2437 },
    },
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    certificationStatus: 'approved',
    availableSlots: ['08:00', '09:00', '13:00', '14:00', '16:00'],
    bio: 'Specialized in treating complex skin conditions and cosmetic dermatology.',
    education: ['MD, Stanford University', 'Residency: UCLA Medical Center'],
    languages: ['English', 'Mandarin'],
  },
  {
    id: '3',
    name: 'Dr. Emily Rodriguez',
    email: 'emily.rodriguez@dermmate.com',
    phone: '+1234567802',
    specialization: 'Nail Disorders, Dermatopathology',
    experience: 15,
    rating: 4.7,
    totalReviews: 312,
    location: {
      city: 'Chicago',
      state: 'IL',
      address: '789 Clinic Street, Suite 150',
      coordinates: { lat: 41.8781, lng: -87.6298 },
    },
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    certificationStatus: 'approved',
    availableSlots: ['10:00', '11:00', '12:00', '15:00', '16:00'],
    bio: 'Expert in nail disorders and dermatopathology with extensive research background.',
    education: ['MD, Northwestern University', 'Fellowship: Mayo Clinic'],
    languages: ['English', 'Spanish', 'French'],
  },
]
