export const mockNotifications = [
  {
    id: '1',
    userId: '1',
    type: 'appointment',
    title: 'Appointment Confirmed',
    message: 'Your appointment with Dr. Sarah Johnson is confirmed for Dec 20, 2024 at 10:00 AM',
    read: false,
    createdAt: '2024-12-15T10:30:00Z',
    link: '/appointments',
  },
  {
    id: '2',
    userId: '1',
    type: 'follow-up',
    title: 'Follow-up Reminder',
    message: 'Your follow-up appointment is scheduled for Dec 22, 2024',
    read: false,
    createdAt: '2024-12-16T09:00:00Z',
    link: '/appointments',
  },
  {
    id: '3',
    userId: '1',
    type: 'case',
    title: 'Case Update',
    message: 'Dr. Sarah Johnson has updated your treatment plan',
    read: true,
    createdAt: '2024-12-10T14:20:00Z',
    link: '/cases',
  },
    {
    id: '4',
    userId: '1',
    type: 'case',
    title: 'Review',
    message: 'Ahsan has submitted a review 3 stars for your consultation',
    read: true,
    createdAt: '2024-12-10T14:20:00Z',
    link: '/cases',
  },
]
